permalink: /:year:month:day/:title
url: #
baseurl: /project

# variables
name: Official Hacker's
description: officialhacker.gq


google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

jekyll_admin: 
 hidden_links: 
  - posts 
  - pages 
  - staticfiles
  - datafiles
  - configuration

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true